### ISSUE TITLE
Optional argument of `dup` ignored.

### ISSUE THREAD

**Issue by jfjlaros** [mutalyzer/mutalyzer#143] opened 2016-01-31 13:04 UTC
The following description is accepted by the name checker:

    NM_002001.2:c.10_12dupGGGGGG

Apparently the optional argument `GGGGGG` is not matched to the reference sequence. This can be solved by using the strategy for checking the optional argument for deletions.

**Comment by martijnvermaat** [comment] 2016-01-31 13:40
Duplicate of https://humgenprojects.lumc.nl/trac/mutalyzer/ticket/128

**Closed** 2016-05-17 13:57 UTC
